#@ load("@ytt:data", "data")

#@ if/end "grype-image-scanner-tekton-task" not in data.values.excluded_blueprints:
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: grype-image-scanner
spec:
  description: Task to scan application image with Grype
  params:
    - name: image
    - name: grype-args
      default:
        - "--fail-on=critical"
        - "--scope=AllLayers"
        - "--only-fixed"
  steps:
    - name: scan
      image: anchore/grype:v0.54.0
      args: ["$(params.image)", "$(params.grype-args[*])", "--config=/workspace/grype/grype.yml"]
      volumeMounts:
        - name: grype-config
          mountPath: /workspace/grype
  volumes:
    - name: grype-config
      secret:
        secretName: grype-config
