#@ load("@ytt:data", "data")

#@ if/end "tekton-source-test-pipelinerun" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-source-test-pipelinerun
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
    revision: spec.params[?(@.name=="source-revision")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      params:
      - name: source-url
        value: $(runnable.spec.inputs.source-url)$
      - name: source-revision
        value: $(runnable.spec.inputs.source-revision)$
      - name: source-subpath
        value: $(runnable.spec.inputs.source-subpath)$
      pipelineRef:
        name: $(selected.metadata.name)$
