#@ load("@ytt:data", "data")

#@ if/end "commit-and-pr-taskrun" not in data.values.excluded_blueprints:
---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: commit-and-pr-taskrun
spec:
  outputs:
    pr-url: status.taskResults[?(@.name=="pr-url")].value
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-commit-and-pr-
      labels: $(runnable.metadata.labels)$
    spec:
      serviceAccountName: $(runnable.spec.inputs.serviceAccount)$
      taskRef:
        name: commit-and-pr
        kind: ClusterTask
      workspaces:
        - name: ws
          emptyDir: {}
      params: $(runnable.spec.inputs.params)$
