#@ load("@ytt:data", "data")

#@ if/end "commit-and-pr-tekton-task" not in data.values.excluded_blueprints:
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: commit-and-pr
spec:
  description: |-
    Consumes application deployment configuration files as a Base64-encoded JSON,
    pushes them to a Git repository under a given path, and opens a pull request
    to merge the changes into a given target branch.
  params:
    - name: repository_owner
      description: The owner of the Git repository (username or organization name).
      type: string
    - name: repository_name
      description: The name of the Git repository.
      type: string
    - name: commit_branch
      description: The branch to use to open a pull request. If empty, a random name is generated.
      type: string
    - name: git_user_email
      description: The email of the user interacting with the Git repository.
      type: string
      default: "cartographer@kadras.io"
    - name: git_user_name
      description: The name of the user interacting with the Git repository.
      type: string
      default: "cartographer"
    - name: git_commit_message
      description: The commit message to use when pushing configuration changes to Git.
      type: string
      default: "Update from Cartographer"
    - name: git_files
      description: The configuration files to push to the Git repository, provided as a Base64-encoded JSON map.
      type: string
    - name: git_server_address
      type: string
      description: The location of the server hosting the specified Git repository.
      default: https://github.com
    - name: git_server_kind
      type: string
      description: The type of Git server where to open the pull request (e.g. github, gitlab, gitea).
      default: github
    - name: pull_request_title
      type: string
      description: The title of the pull request.
    - name: pull_request_body
      type: string
      description: The message body of the pull request.
      default: ""
    - name: base_branch
      type: string
      description: The target branch where to push configuration changes.
      default: main
    - name: sub_path
      description: The path in the Git repository where to write the configuration files.
      type: string
      default: "config"
  results:
    - name: pr-url
      description: The URL of the successfully created pull request.
  workspaces:
    - name: ws
      mountPath: /workspaces/ws
  steps:
    - name: ensure-base-branch-exists
      image: paketobuildpacks/build-jammy-base:0.1.46
      workingDir: /tekton/home
      script: |
        #!/usr/bin/env bash

        set -o errexit
        set -o pipefail

        cd `mktemp -d`

        set +o xtrace # Avoid leaking secrets, echo sensitive lines

        echo 'git_prefix=$(cat $(credentials.path)/.git-credentials)'
        git_prefix=$(cat $(credentials.path)/.git-credentials)

        echo 'git_repository="$git_prefix/$(params.repository_owner)/$(params.repository_name).git"'
        git_repository="$git_prefix/$(params.repository_owner)/$(params.repository_name).git"

        echo 'git clone --depth 1 "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g'
        git clone --depth 1 "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g"

        set -o xtrace
        cd ./repo

        if git ls-remote --exit-code --heads origin "$(params.base_branch)"; then
          echo "branch exists"
        else
          git checkout --orphan "$(params.base_branch)"
          git rm --cached . -r || true
          git config user.email "$(params.git_user_email)"
          git config user.name "$(params.git_user_name)"
          git commit -m "Initialize branch" --allow-empty
          git push origin $(params.base_branch)
        fi

    - name: git-clone-and-push
      image: paketobuildpacks/build-jammy-base:0.1.46
      workingDir: /tekton/home
      script: |
        #!/usr/bin/env bash

        set -o errexit

        cd `mktemp -d`

        commit_branch="$(params.commit_branch)"
        if [ -z "$commit_branch" ]; then
          commit_branch=$(date +%s | base64)
        fi

        set +o xtrace # Avoid leaking secrets, echo sensitive lines

        echo 'git_prefix=$(cat $(credentials.path)/.git-credentials)'
        git_prefix=$(cat $(credentials.path)/.git-credentials)

        echo 'git_repository="$git_prefix/$(params.repository_owner)/$(params.repository_name).git"'
        git_repository="$git_prefix/$(params.repository_owner)/$(params.repository_name).git"

        echo 'git clone --depth 1 -b "$commit_branch" "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g'
        echo 'Check to see if the git clone failed. If so, retry.'
        git clone --depth 1 -b "$commit_branch" "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g"
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          set -o xtrace
          cd ./repo
        else
          echo 'git clone --depth 1 "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g"'
          git clone --depth 1 "$git_repository" ./repo 2>&1 | sed "s|$git_prefix|REDACTED|g"
          set -o xtrace
          cd ./repo
          git checkout -b "$commit_branch"
        fi

        git config user.email "$(params.git_user_email)"
        git config user.name "$(params.git_user_name)"

        mkdir -p $(params.sub_path) && rm -rf $(params.sub_path)/*
        cd $(params.sub_path)

        echo '$(params.git_files)' | base64 --decode > files.json
        eval "$(cat files.json | jq -r 'to_entries | .[] | @sh "mkdir -p $(dirname \(.key)) && echo \(.value) > \(.key) && git add \(.key)"')"

        git commit -m "$(params.git_commit_message)" --allow-empty
        git push origin $commit_branch

        echo "$commit_branch" > /workspaces/ws/commit_branch

    - name: open-pr
      image: ghcr.io/jenkins-x/jx-scm
      script: |
        #!/usr/bin/env bash

        set -o errexit
        set -o pipefail

        head_branch=$(cat /workspaces/ws/commit_branch | tr -d '\n')

        token=$(cat $(credentials.path)/.git-credentials | sed -e 's/https:.*://' | sed -e 's/@.*//')

        jx-scm pull-request create \
          --kind "$(params.git_server_kind)" \
          --server "$(params.git_server_address)" \
          --token "$token" \
          --owner "$(params.repository_owner)" \
          --name "$(params.repository_name)" \
          --head "$head_branch" \
          --title "$(params.pull_request_title)" \
          --body "$(params.pull_request_body)" \
          --base "$(params.base_branch)" \
          --allow-update 2>&1 |
        tee stdoutAndSterr.txt

        cat stdoutAndSterr.txt | sed -n -e 's/^.*\. url: //p' > $(results.pr-url.path)
