apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.0.0
spec:
  refName: cartographer-blueprints.packages.kadras.io
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        excluded_blueprints:
          type: array
          description: A list of blueprints and manifests to esclude from being applied.
          items:
            type: string
            default: ""
          default: []
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io
spec:
  displayName: cartographer-blueprints
  longDescription: A set of reusable blueprints for Cartographer, a Kubernetes-native framework to build paved paths to production.
  shortDescription: A set of reusable blueprints for Cartographer.
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix
  categories:
  - developer experience
  - ci/cd
  - platform engineering

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cartographer-blueprints
spec:
  packageRef:
    refName: cartographer-blueprints.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
