apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: cartographer-blueprints.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/cartographer-blueprints/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: cartographer-blueprints.packages.kadras.io
spec:
  displayName: cartographer-blueprints
  longDescription: A set of reusable blueprints to build paved paths to production on Kubernetes using Cartographer.
  shortDescription: A set of reusable blueprints for Cartographer.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  categories:
  - ci/cd
  - golden paths
  - developer experience
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/cartographer-blueprints
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: cartographer-blueprints
spec:
  packageRef:
    refName: cartographer-blueprints.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
